[package]
name = "xplode-game"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = "0.4"
alloy-primitives = "0.6"
alloy-sol-types = "0.6"

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "s"